### PR TITLE
npm update xterm

### PR DESCRIPTION
**Pull request by cockpituous**
Check for any outstanding update of point version of any outstanding NPM package dependency
 * [ ] FAIL: npm-update

### CODE REVIEW

**Comment by cockpituous** [comment]
npm-update moment done: https://github.com/cockpituous/cockpit-podman/commits/npm-update-moment-20200913-152121

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```
package.json:    "xterm": "4.9.0"
src/ContainerLogs.jsx:import { Terminal } from "xterm";
src/ContainerTerminal.css:@import "~xterm/css/xterm.css";
src/ContainerTerminal.jsx:import { Terminal } from "xterm";
test/check-application:        b.wait_text(".container-logs .xterm-accessibility-tree > div:nth-child(1)", "1")
test/check-application:        b.wait_text(".container-logs .xterm-accessibility-tree > div:nth-child(6)", "6")
test/check-application:        b.wait(lambda: get_int(b.text(".container-terminal .xterm-accessibility-tree > div:nth-child(3)")) > 7)
test/check-application:        b.wait_text(".pf-m-expanded .xterm-accessibility-tree > div:nth-child(1)", "/ # ")
test/check-application:        b.focus(".pf-m-expanded .xterm-helper-textarea")
test/check-application:        b.wait_text(".pf-m-expanded .xterm-accessibility-tree > div:nth-child(2)", "hello")
test/check-application:        b.wait_text(".pf-m-expanded .xterm-accessibility-tree > div:nth-child(3)", "/ # ")
test/check-application:        b.wait_text(".pf-m-expanded .xterm-accessibility-tree > div:nth-child(1)", "/ # echo hello")
test/check-application:        b.wait_text(".pf-m-expanded .xterm-accessibility-tree > div:nth-child(3)", "/ #  disconnected ")
test/check-application:        b.wait_text(".pf-m-expanded .xterm-accessibility-tree > div:nth-child(1)", "/ # ")
```

**Comment by cockpituous** [comment]
npm-update in progress on centosci-tasks-nh612.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/npm-update-533-20200913-151919/

**Comment by cockpituous** [comment]
npm-update in progress on centosci-tasks-8kzv0.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/npm-update-533-20200913-151919/

**Comment by cockpituous** [comment]
Error accessing /repos/cockpit-project/cockpit-podman/pulls
  Status: 422
  Reason: Unprocessable Entity
  Response: {"message":"The specified issue is already attached to a pull request.","errors":[{"value"None,"resource":"PullRequest","field":"issue","code":"invalid"}],"documentation_url":"https://docs.github.com/rest/reference/pulls#create-a-pull-request"}: https://logs-https-cockpit.apps.ci.centos.org/logs/npm-update-533-20200913-151919/

**Review by martinpitt — APPROVED** [review]
Tested visually, works fine.

**Pull request merged**
