### PR TITLE
test: update expected strings in sudo prompt

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
This got a UI overhaul recently, so just our tests accordingly.

 - [x] https://github.com/cockpit-project/cockpit/pull/15840

### CODE REVIEW

**Review by martinpitt — APPROVED** [review]
Nice, thank you! (assuming green)

**Review by martinpitt — APPROVED** [review]
Danke!

**Comment by allisonkarlitskaya** [comment]
Still not there yet, unfortunately :(

Will test locally to see what's up.

**Comment by allisonkarlitskaya** [comment]
```
    def system_before(self, version):
        try:
            v = self.machine.execute("rpm -q --qf '%{V}' cockpit-system").split(".")
        except subprocess.CalledProcessError:
            return False

        return int(v[0]) < version
```

ugh.

**Comment by martinpitt** [comment]
After the cockpit fix lands, you'll need to bump the test/common checkout in the Makefile to grab that SHA instead of the fixed version there.

**Review by martinpitt — APPROVED** [review]

**Comment by allisonkarlitskaya** [comment]
The fail statuses are broken — the test log confirms all tests passed (twice now, even, for both rhel-8-4 and fedora-34/rawhide).  This is an infra issue.

**Pull request merged**
