### PR TITLE
Bump cockpit repo to 284

### LINKED ISSUE #1189: Python bridge support
```
warning: watching is not implemented, use fswatch1
```

image

This is from the `FileAutoComplete` component from Cockpit.

Allowed Messages needs to be extended with:
```
asyncio-ERROR: Task was destroyed but it is pending!
```

### PR DESCRIPTION
**Pull request by martinpitt**
This picks up a FileAutoComplete fix for running with the Python bridge.
(Fixes #1189)

This also picks up the "ugly zero" font fix from tabular numbers. Adjust
pixel tests accordingly.

Disable the "RTL" scenario, as it's still causing unstable reference
images, and we don't yet know what exactly to do with that in Cockpit.

----

[pixel diff review](https://github.com/cockpit-project/pixel-test-reference/compare/74726a02181df013735b9f6a65e91fa1ab5a065f..cbd9c8ffa95e7ac154adc2a29e3eb9d363b69652)

### CODE REVIEW

**Comment by martinpitt** [comment]
284 isn't released yet, but current state of cockpit main won't change shared components any more today (too risky)

**Review by jelly — DISMISSED** [review]

**Comment by martinpitt** [comment]
Ah, [new RTL pixels](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1192-20230125-091815-b5147058-fedora-37/log.html). I'm running out of time right now, will update this afternoon (unless @jelly beats me to it)

**Review by jelly — APPROVED** [review]

**Comment by martinpitt** [comment]
Updated again -- the "almost" is now "exactly", no other effective changes.

**Review by jelly — DISMISSED** [review]

**Comment by martinpitt** [comment]
Sorry @jelly, had to update this again. RTL is still causing too much headache here.

**Review by KKoukiou — APPROVED** [review]

**Pull request merged**
