### PR TITLE
fix: Unsupported style property row-gap. Did you mean rowGap?

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Comment by KKoukiou** [comment]
Actually is that even needed?

**Review by garrett — APPROVED** [review]
I don't see any visible difference between this and main. If it's being ignored and isn't (apparently) needed, then this is perfect. :+1:

**Comment by jelly** [comment]
> I don't see any visible difference between this and main. If it's being ignored and isn't (apparently) needed, then this is perfect. +1

Did you see https://cockpit-logs.us-east-1.linodeobjects.com/pull-1162-20221215-141136-7390a520-fedora-36/pixeldiff.html#TestApplication-testBasicSystem-overview-mobile one pixel test changed

**Review by garrett — DISMISSED** [review]
OH! If that pixel test is to be believed (and I'm sure it is), then this is a mobile thing, I guess, and it was being applied! Whoops.

Thanks for spotting that, @jelly!

Ideally, we wouldn't use a style. But if we are, then I guess it needs to be the following?

```jsx
style={{ rowGap: "var(--pf-global--spacer--xs)" }}>
```

**Review by tomasmatus — APPROVED** [review]
Thanks!

**Pull request merged**
