### PR TITLE
Upgrade to react 18 and enable the new concurrent renderer

### PR DESCRIPTION
**Pull request by KKoukiou**
https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis

### CODE REVIEW

**Comment by jelly** [comment]
So the workflow fails as the workflow tries to re-create the node_modules commit you made by running `npm install` and comparing the created hash which fails.

As the bots also cannot build cockpit, it seems you somehow created a broken `node_modules` locally?

**Comment by jelly** [comment]
Seems the functionality which keeps sets the `window.location` is broken in the React upgrade.

**Comment by KKoukiou** [comment]
> Seems the functionality which keeps sets the `window.location` is broken in the React upgrade.

setState Batching changed behavior in this release. I am sure this is that. I am investigating right now.

**Review by jelly — APPROVED** [review]

**Comment by jelly** [comment]
Rawhide fails due to the new cockpit disallowing root login, fix has been submitted https://github.com/cockpit-project/cockpit-podman/pull/1145

**Pull request merged**
