### PR TITLE
Drop the already fixed pod event

### PR DESCRIPTION
**Pull request by jelly**

### CODE REVIEW

**Review by marusak — APPROVED** [review]
Thanks!  We have test for it, right?

**Comment by marusak** [comment]
https://github.com/KKoukiou/cockpit-podman/commit/db3159232fbd97740707283460943fd2aac3a620

Also the other line should be dropped?

**Comment by marusak** [comment]
If you would add check that the pod is running here after one container is added to it then it would be tested.
https://github.com/cockpit-project/cockpit-podman/blob/main/test/check-application#L215

**Comment by jelly** [comment]
> 



> [KKoukiou@db31592](https://github.com/KKoukiou/cockpit-podman/commit/db3159232fbd97740707283460943fd2aac3a620)
> 
> Also the other line should be dropped?

Hmm need to investigate.

**Comment by jelly** [comment]
> If you would add check that the pod is running here after one container is added to it then it would be tested. https://github.com/cockpit-project/cockpit-podman/blob/main/test/check-application#L215

Seems it is still broken so my testing was wrong... Test on Fedora-36


image

Just added `b.wait_visible("#table-pod-1 .ct-badge-pod-running")`

**Pull request closed without merging**
