### PR TITLE
Add testing on ubuntu-stable

### PR DESCRIPTION
**Pull request by martinpitt**
cockpit-podman is in Ubuntu now, so let's make sure it stays working.

### CODE REVIEW

**Comment by martinpitt** [comment]
I locally ran `TEST_OS=ubuntu-stable make check` and it succeeded. I'm happy to add that to our testmap as well, if you prefer that over running on Travis.

**Comment by marusak** [comment]
Cool!!
Can we have `Fixes #481` ?
I'll wait for test results before approving.
I don't mind travis, but at least it should be in `__manual__`

**Comment by martinpitt** [comment]
@marusak: Indeed, I closed #481 now. That happened independent from this PR. I sent https://github.com/cockpit-project/bots/pull/1353 to add it to testmap, _manual is a good idea.

**Review by marusak — APPROVED** [review]
nice, thanks!

**Pull request merged**
