### PR TITLE
Check for NPM dependency updates

### PR DESCRIPTION
**Pull request by cockpituous**
Check for any outstanding update of point version of any outstanding NPM package dependency
 * [ ] FAIL: npm-update

### CODE REVIEW

**Comment by cockpituous** [comment]
Error accessing /repos/cockpit-project/cockpit-podman/pulls
  Status: 422
  Reason: Unprocessable Entity
  Response: {"message":"The specified issue is already attached to a pull request.","errors":[{"value"None,"resource":"PullRequest","field":"issue","code":"invalid"}],"documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}: https://209.132.184.41:8493/logs/npm-update-141-20190709-004545/

**Comment by cockpituous** [comment]
npm-update patternfly done: https://github.com/cockpituous/cockpit-podman/commits/npm-update-patternfly-20190709-004646

**Comment by cockpituous** [comment]
Error accessing /repos/cockpit-project/cockpit-podman/pulls
  Status: 422
  Reason: Unprocessable Entity
  Response: {"message":"The specified issue is already attached to a pull request.","errors":[{"value"None,"resource":"PullRequest","field":"issue","code":"invalid"}],"documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}: https://209.132.184.41:8493/logs/npm-update-141-20190709-004545/

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```
package.json:    "xterm": "3.14.4"
src/ContainerTerminal.css:@import "~xterm/lib/xterm.css";
src/ContainerTerminal.jsx:import { Terminal } from "xterm";
test/check-application:            b.wait_in_text(".xterm-accessibility-tree > div:nth-child(2)", "Hello World")
test/check-application:            b.wait_text(".xterm-accessibility-tree > div:nth-child(1)", "/ # ")
test/check-application:            b.wait_text(".xterm-accessibility-tree > div:nth-child(2)", "hello")
test/check-application:            b.wait_text(".xterm-accessibility-tree > div:nth-child(3)", "/ # ")
test/check-application:            b.wait_text(".xterm-accessibility-tree > div:nth-child(1)", "/ # echo hello")
test/check-application:            b.wait_text(".xterm-accessibility-tree > div:nth-child(3)", "/ #  disconnected ")
test/check-application:            b.wait_text(".xterm-accessibility-tree > div:nth-child(1)", "/ # ")
```

**Comment by marusak** [comment]
See #140

**Pull request closed without merging**
