### PR TITLE
test: Adjust checkpoint tests for debian-testing

### PR DESCRIPTION
**Pull request by martinpitt**
criu is not in Debian testing, and will not be for a while:
https://bugs.debian.org/796536

Ensure that the UI shows a proper error message there.

### CODE REVIEW

**Comment by marusak** [comment]
This is of course fine, just wonder how it behaves when criu is not present. Just those buttons are missing? Would it be worth checking that they are not present on debian - then we will notice once they are present and we can verify it works as expected.

**Comment by martinpitt** [comment]
@marusak : Good point. They actually are present, but then cause a dialog that says "needs criu of at least version XXX". criu is available in unstable. So the page could check if the `criu` command is available and otherwise not show the menu entry; or we leave it there for discoverability.

**Comment by marusak** [comment]
> They actually are present, but then cause a dialog that says "needs criu of at least version XXX". criu is available in unstable. So the page could check if the criu command is available and otherwise not show the menu entry; or we leave it there for discoverability.

Error that is clear is fine. It will show users that they miss something and they may install it or rise it with upstream to get this delivered. I suggest just checking this error in tests for debian.

**Comment by martinpitt** [comment]
Whoops, [ambiguous selector](https://logs.cockpit-project.org/logs/pull-470-20200731-092820-34312228-debian-testing/log.html#4-2), I didn't get that locally.

**Comment by martinpitt** [comment]
Still [one unexpected message](https://logs.cockpit-project.org/logs/pull-470-20200731-114148-aa67fa3d-debian-testing/log.html#4) which I don't get locally, but in general the test is working.

**Comment by martinpitt** [comment]
The two checkpoint tests now succeeded on Debian. @marusak , could you please review?

**Pull request merged**
