### PR TITLE
Dynamically update cpu and memory info

### LINKED ISSUE #376: CPU and memory usage is static
`podman top` shows cpu usage 98.309%,  but cockpit-podman show cpu usage 0%, and seems not changing anyway.
image

image

### PR DESCRIPTION
**Pull request by EricJeffrey**
Fix #376

### CODE REVIEW

**Comment by EricJeffrey** [comment]
well, something wrong with the 'cgroup v2 not support' part, checking now

**Comment by marusak** [comment]
> well, something wrong with the 'cgroup v2 not support' part, checking now

How do you mean? I haven't noticed any problem with cgroupsV2.

**Comment by EricJeffrey** [comment]
@marusak `app.jsx > updateContainerStats > catch`, the if statement `if (ex.cause == "no support for CGroups V1 in rootless environments") ` won't work actually. the `ex` argument is not as I expected. It is:
```
{status: 500, reason: "Internal Server Error", message: "Failed to obtain Container e937b97031d60bf70ad8bef…o support for CGroups V1 in rootless environments", problem: null, valueOf: ƒ, …}
```
But if I do `curl` in cli, it shows this:
```json
{"cause":"no support for CGroups V1 in rootless environments","message":"Failed to obtain Container uhalo stats: unable to load cgroup at /libpod_parent/libpod-e937b97031d60bf70ad8bef21373059956ff6f401f3d577c950c5db77ea3e07c: no support for CGroups V1 in rootless environments","response":500}
```

**Comment by marusak** [comment]
right, can you please just check that `message` contains this substring?

**Comment by EricJeffrey** [comment]
Well I've located the problem and seems `manage_error` need a change:
```js
function manage_error(reject, error, content) {
    let message = "";
    if (content) {
        try {
            message = JSON.parse(content).message;
        } catch (e) {
            message = content;
        }
    }
    const c = { ...error };
    if (message)
        c.message = message;
    reject(c);
}
```
The `cause` filed is in `content`, should we extract it out like this?:
```js
function manage_error(reject, error, content) {
    let message = "";
    let cause = "";
    if (content) {
        try {
            const content_parsed = JSON.parse(content);
            message = content_parsed.message;
            cause = content_parsed.cause;
        } catch (e) {
            message = content;
        }
    }
    const c = { ...error };
    if (message)
        c.message = message;
    if (cause)
        c.cause = cause;
    reject(c);
}
```
😂 Not very cool, any better idea?

**Comment by EricJeffrey** [comment]
trying to clean up redundant commits, failed 😂

**Comment by EricJeffrey** [comment]
Looks like work now. Anyway, how should I do the integration test? Just run command and see whether it goes well as you said all by myself?

**Comment by marusak** [comment]
> The cause filed is in content, should we extract it out like this?:

We could just take everything from `content` and put it into `c`. So something like:
```js
 if (content) {
        let content_o = {};
        try {
            content_o = JSON.parse(content);
        } catch {
            content_o.message = content;
        }
    }
    const c = { ...error, ...content_o };
```

> Anyway, how should I do the integration test? Just run command and see whether it goes well as you said all by myself?

If you don't feel like writing those tests, I'll gladly help with that.
To start, [here](https://github.com/cockpit-project/starter-kit#automated-testing)  is how to prepare VM and how to run tests.
It should go into `test/check-application`, not sure where exactly, maybe it could be a separate test.
Some pointers:
1. search for `podman run` in the file to see, how to run new container
2. search for `cpu =` to see, how we read the value from the UI

**Comment by EricJeffrey** [comment]
Ok got it, I'll take a try about the test.

**Comment by EricJeffrey** [comment]
Well, you take the test part. 😂 `make check` doesn't work on my Ubuntu20 Server, and got no idea about the error message.

**Comment by marusak** [comment]
Taking over this. I'll write tests and make commits fit our style.

**Comment by EricJeffrey** [comment]
Also noticed sometimes the `client.streamEvents` will catch a `truncated response` exception, causing the `systemServiceAvailable` or `userServiceAvailable` changed. I tried to reproduce, but failed sometime. Don't know if it is related to my `podman.socket` (I wrote the systemd unit file by myself).

**Comment by marusak** [comment]
Pushed version with test and polished commits. Also triggering tests.

**Comment by marusak** [comment]
> Also noticed sometimes the client.streamEvents will catch a truncated response exception, causing the systemServiceAvailable or userServiceAvailable changed. I tried to reproduce, but failed sometime. Don't know if it is related to my podman.socket (I wrote the systemd unit file by myself).

Yeah, this smells like podman coredumping. When that happens, can you check journal if there is some info?

**Comment by marusak** [comment]
@martinpitt or @KKoukiou can you please review since I touched this? Thanks!

**Comment by EricJeffrey** [comment]
@marusak Mostly it happen when I try to stop/start more than one containers in a short time. I look up the log by `journalctl -xe` but no very useful message found.

**Pull request merged**
