### PR TITLE
Use standard PF4 selects

### PR DESCRIPTION
**Pull request by marusak**
No visual change really.

### CODE REVIEW

**Comment by marusak** [comment]
Also testing `fedora-33/rawhide`

**Review by martinpitt — APPROVED** [review]
Nice!

**Comment by martinpitt** [comment]
Also good to see that f33/rawhide doesn't fare too bad, there just seems to be a rawhide regression wrt. checkpoint/restore?

**Comment by marusak** [comment]
> Also good to see that f33/rawhide doesn't fare too bad, there just seems to be a rawhide regression wrt. checkpoint/restore?

Hopefully https://github.com/containers/crun/issues/560 will help

**Pull request merged**
