### PR TITLE
test: extend rename dialog test coverage

### PR DESCRIPTION
**Pull request by jelly**
Test the error conditions, and submitting the rename modal via an enter key.

### CODE REVIEW

**Comment by jelly** [comment]
Should cover most of https://cockpit-logs.us-east-1.linodeobjects.com/pull-1354-20230713-111536-64696d17-fedora-38-devel/Coverage/src/ContainerRenameModal.jsx.gcov.html

**Comment by jelly** [comment]
91% coverage now :partying_face:

**Review by martinpitt — DISMISSED** [review]
> this is basically "unreachable" code

Right, then I suppose it could just be removed. The test clearly covers this case. I leave it up to you if you want to do that here (I'm happy to re-approve quickly) or in a follow-up. Thanks!

**Comment by jelly** [comment]
> > this is basically "unreachable" code
> 
> Right, then I suppose it could just be removed. The test clearly covers this case. I leave it up to you if you want to do that here (I'm happy to re-approve quickly) or in a follow-up. Thanks!

But it isn't dead code! If you submit via the enter key we should handle that as well.

**Comment by jelly** [comment]
> [Noooice!](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1359-20230720-071540-95dfbc7e-fedora-38-devel/Coverage/src/ContainerRenameModal.jsx.gcov.html)

Need to discuss improving the `not-covered` with @mvollmer as it would be nice if it could recognize blocks.

**Pull request merged**
