### PR TITLE
Add integration tests in FMF format

### PR DESCRIPTION
**Pull request by martinpitt**
This will allow us to use the same test execution scripts for downstream
gating and upstream PRs via packit. Copy browser.sh and run-test.sh from
Fedora's downstream gating tests, and adjust browser.sh's path variables
to work for both STI and FMF.

Enable GitHub PR integration.

See https://docs.fedoraproject.org/en-US/ci/tmt/ for details.

------

 - [x] rebase after #648
 - [x] wait for https://github.com/packit/sandcastle/pull/90 to get rolled out (asked in that PR)
 - [x] fix [incomplete logs](https://github.com/packit/packit-service/issues/917)
 - [x] increase sandcastle memory to fix webpack OOM: https://github.com/packit/sandcastle/pull/92 (not rolled out yet)
 - [x] rebase on top of #656 
 - [x] apply the browser.sh changes to downstream in a PR, and ensure that they get in sync: https://src.fedoraproject.org/rpms/cockpit-podman/pull-request/17
 - [x] unbreak packit test runs: https://github.com/packit/packit/issues/1078
 - [x] enable all Fedora versions

I am currently testing this with

    bots/vm-run fedora-33
    tmt -v run --all provision --how connect --guest c

It would be much more elegant to test with just `tmt run`, but that [requires system libvirt](https://bugzilla.redhat.com/show_bug.cgi?id=1914194) which I don't have on my system. The tests generally work, but I see a bunch of failures still.

### CODE REVIEW

**Comment by martinpitt** [comment]
Heh, the [srpm build fails](https://prod.packit.dev/srpm-build/11929/logs), we really need #648.

**Comment by martinpitt** [comment]
@marusak: The [srpm build](https://prod.packit.dev/srpm-build/11933/logs) still failed with "did not output a path to the generated archive", although it clearly did now. Does that ring a bell? is that still possibly the sassc issue, that the build did not really succeed?

**Comment by marusak** [comment]
> The srpm build still failed with "did not output a path to the generated archive", although it clearly did now. Does that ring a bell? is that still possibly the sassc issue, that the build did not really succeed?

I ran it locally and it worked. When I ran it in sandbox container it fails with missing sassc. It does not show that due to https://github.com/packit/packit-service/issues/917 and since it fails, there really isn't any archive.

**Comment by marusak** [comment]
This can be rebased now

**Comment by martinpitt** [comment]
Thanks @marusak! Now we need to wait until https://github.com/packit/sandcastle/pull/90 gets rolled out to production, I asked there.

**Comment by martinpitt** [comment]
[Latest prod build of sandcastle](https://hub.docker.com/r/usercont/sandcastle/builds) includes sassc, trying again.

**Comment by martinpitt** [comment]
Synced to current cockpit-podman Fedora dist-git, and rebased to current master. (I don't expect this to work yet, though)

**Comment by martinpitt** [comment]
@TomasTomecek : "Building SRPM" has been hanging for 1 hour without starting or giving a log URL. Is that COPR part known-broken again as well?

**Comment by martinpitt** [comment]
Rebasing to current master, let's probe packit again.

**Comment by TomasTomecek** [comment]
> @TomasTomecek : "Building SRPM" has been hanging for 1 hour without starting or giving a log URL. Is that COPR part known-broken again as well?

I saw this with an anaconda PR today, gonna finally file an issue for this.

**Comment by thrix** [comment]
We are looking into why the results were not propagated here:

https://gitlab.com/testing-farm/nucleus/-/issues/15#note_511322794

Rerunning the tests ...

**Comment by thrix** [comment]
interesting, seems the problem is reproducable :)

**Comment by TomasTomecek** [comment]
HTTP is hard https://github.com/packit/packit-service/issues/987

**Comment by martinpitt** [comment]
Whee, the first [successful test run on packit](http://artifacts.dev.testing-farm.io/6970a696-cd86-4676-a109-d1dd491611e8/)! :tada:

**Comment by martinpitt** [comment]
Meh, our [chromium downgrade hack](http://artifacts.dev.testing-farm.io/72712bf4-06bf-48e1-b6ff-7d1513128a57/) gets in the way again for running this everywhere. Trying to install the F32 version, let's see how that works. But I think it'd really be better to [find a better hack](https://github.com/cockpit-project/cockpit/pull/15352), I'll look into that again.

**Comment by martinpitt** [comment]
F34 tests never get started, I reported this in https://github.com/packit/packit-service/issues/975

**Comment by martinpitt** [comment]
Behold! All tests are green! [rawhide](http://artifacts.dev.testing-farm.io/9c0451ba-f950-4b05-932e-87ff83c86c50/).

I think this is ready to land then -- it's no worse than what we have in master right now, and I'd like to land the test scripts into an upstream release, so that we can use them in the downstream dist-git gating tests.

**Comment by TomasTomecek** [comment]
this is awesome @martinpitt! so glad you got :green_apple: for rawhide, that is so important

We are aware of both issues (F34 build and TF test results not being correctly reported back to PRs) and they are actively being worked on this sprint - I hope this should be fixed next week :rocket:

**Review by marusak — APPROVED** [review]
Nice!
What is the plan about having the same files in downstream and upstream? Can we have just one copy?

**Comment by martinpitt** [comment]
@marusak : That's excactly the plan -- I'd like to do a release with this, then hammer on the dist-git gating to remove the tests/ directory and the whole STI wrapping. I suppose we may need to put some skeleton FMF into dist-git, but figuring that out will be my next task. But for sure we can share run-tests.sh and browser.sh, which already helps a lot -- these are the two files that change all the time.

**Comment by martinpitt** [comment]
@TomasTomecek : Thanks for your help and all the fixes! I feel this is finally coming together, and I'm really looking forward to using this much more.

**Pull request merged**
