### PR TITLE
Adding support for PPC64LE

### PR DESCRIPTION
**Pull request by ezeeyahoo**
Hi,

I have tested these changes included to support PPC64LE and request you for a review.

Thanks

### CODE REVIEW

**Comment by marusak** [comment]
May I ask why do you need this?
We dropped `.travis.yml` file from other cockpit projects and maybe it is time to do the same for c-podman. We surely won't do that if there are users that need it, but if it is not necessary to keep it in the repository, then I vote for removing it.

**Comment by gerrith3** [comment]
@marusak this project happens to be a part of the Red Hat distributions, including their ppc64le builds.  We are enabling upstream CI for those to help reduce the cost of maintaining/debugging issues and to ensure the port stays current on ppc64le.  If you dropped .travis.yml from other projects, what CI are you using?  We have very few that support Power today (jenkins, Travis, and possible github actions).  We would like to stay in sync with what you are already doing as much as possible.

**Comment by martinpitt** [comment]
@ezeeyahoo : That travis config won't do anything useful, I'm afraid. The build process is merely about calling `npm install` and `webpack`, none of which is particularly architecture specific or interesting -- and it will be completely irrelevant for actually *running* cockpit-podman.noarch.rpm on e.g. ppc64el, as the official RPM builds use the release tarballsl.

What *would* be useful is to run the integration tests on non-x86 hardware for sure! We don't have hardware for this right now. A while ago I was playing around with running integration tests in travis/semaphore/github actions, but these are usually hampered by not exposing /dev/kvm to the test environment. We can only meaningfully test cockpit-* in VMs, not some random ubuntu container on travis/semaphore.

**Comment by gerrith3** [comment]
@martinpitt We do provide free open source access to Power VMs at http://osuosl.org/powerdev - let me know if you are interested and I'd be willing to be your IBM sponsor.  That would be a real Power8 or Power9 VM.

**Pull request closed without merging**
