### PR TITLE
Change delete container modal using patternfly-react

### PR DESCRIPTION
**Pull request by QiWang19**

### CODE REVIEW

**Comment by QiWang19** [comment]
@KKoukiou PTAL

**Comment by QiWang19** [comment]
@KKoukiou PTAL

**Comment by KKoukiou** [comment]
Super! Only with that version of patternfly-react I get warnings about the imports in console.
I tried with "patternfly-react": "^1.19.1" and it works as expected.
Do you mind taking a look?

**Comment by QiWang19** [comment]
I'll open another PR to remove the reactstrap :)

**Pull request merged**
