### PR TITLE
test: Update to reworked pixel test machinery

### PR DESCRIPTION
**Pull request by mvollmer**
Now assert_pixels will also check the mobile layout.

### CODE REVIEW

**Comment by mvollmer** [comment]
Draft because we might want to catch up even further than just the reworked machinery.

**Comment by mvollmer** [comment]
The `orrible 748cfe36086cdd7069c698d0193a1b4751a1b80e

**Review by marusak — APPROVED** [review]
Thanks!

**Comment by marusak** [comment]
testing farm f-35 is busted - Martin it looking at it in https://github.com/cockpit-project/cockpit-podman/pull/900

**Pull request merged**
