### PR TITLE
Fix updates-testing scenario for F39

### LINKED ISSUE #1464: Nightly tests did not succeed on fedora-39/updates-testing
Tests failed on 7cec14c76d61b35156838c7ab54a60a5a9ead92e, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20231028-014327-7cec14c7-fedora-39-updates-testing//log.html)

### PR DESCRIPTION
**Pull request by martinpitt**
Fixes #1464

### CODE REVIEW

**Comment by martinpitt** [comment]
OH dear, there's [some regression](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1465-20231028-061020-3f099ed7-fedora-39-updates-testing/log.html#32) in F39 updates. @jelly do you have some time to track this down?

**Comment by jelly** [comment]
> OH dear, there's [some regression](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1465-20231028-061020-3f099ed7-fedora-39-updates-testing/log.html#32) in F39 updates. @jelly do you have some time to track this down?

So taking a look, this is all `console.error` from the `packagekit` page.
```
error: Tracer failed: "{"problem":"access-denied","exit_status":null,"exit_signal":null,"message":"Not permitted to perform this action."}", data: "undefined"
```

We don't have this in the allow list, because Cockpit changed the code but did not make it into a release yet.

**Comment by martinpitt** [comment]
Ah, it's the update to updates-testing:
```
Installing weak dependencies:
 cockpit-networkmanager              noarch  303-1.fc39                 updates-testing  825 k
 cockpit-packagekit                  noarch  303-1.fc39                 updates-testing  1.0 M
 cockpit-storaged                    noarch  303-1.fc39                 updates-testing  919 k
```
Somehow F38 didn't do that. Let's not do that, these really shouldn't be installed for podman tests.

**Comment by jelly** [comment]
To be fixed in https://github.com/cockpit-project/cockpit/pull/19546

**Comment by martinpitt** [comment]
Thanks! I'll apply the same fix here. Feel free to push it if you want to, I have a meeting now.

**Review by jelly — APPROVED** [review]

**Pull request merged**
