### PR TITLE
fmf: Test fixes

### PR DESCRIPTION
**Pull request by martinpitt**

### CODE REVIEW

**Comment by martinpitt** [comment]
This will hopefully fix [this failure](http://artifacts.dev.testing-farm.io/fed79b74-6482-495b-95e0-151e34e29f24/) that we saw in the recent PRs.

**Comment by martinpitt** [comment]
:thinking: [That run](http://artifacts.dev.testing-farm.io/721a441b-0807-4ebd-a3b1-594f7b5dd95f/) *did* upgrade from the broken selinux-policy 35.10 to 35.11, but it's still failling. It's most definitively SELinux, the first test succeeds, all subsequent ones fail, and the [journal](http://artifacts.dev.testing-farm.io/721a441b-0807-4ebd-a3b1-594f7b5dd95f/work-allYV3uMw/plans/all/execute/data/test/browser/logs/TestApplication-testBasicSystem-fedora-35-127.0.0.1-22-FAIL.log.gz) has that well-known SELinux violation.

The [TF log](http://artifacts.dev.testing-farm.io/721a441b-0807-4ebd-a3b1-594f7b5dd95f/work-allYV3uMw/log.txt) shows that it's running on cockpit-260.

**Comment by martinpitt** [comment]
When running tmt locally, the image that it (freshly!) downloads starts out with selinux-policy-35.3-1, so *much* older. With this PR it still upgrades to 35.11. However, it then fails on

    ./browser.sh: line 13: TMT_TREE: unbound variable

Let's make this optional, so that we can run `tmt` locally. Added as separate commit.

**Comment by martinpitt** [comment]
Meh, so even the systemctl daemon-reexec [did not help](http://artifacts.dev.testing-farm.io/a92d983f-ec2b-4077-92f4-82b4e8b1efc2/). Sigh, we just need to wait for a new image?

**Comment by martinpitt** [comment]
There is an [additional problem](http://artifacts.dev.testing-farm.io/d2b9b656-0d7b-487e-96d1-e59e0b81b1ad/) now:
```
Error: please update to v2.0.24 or later: outdated conmon version
```

So let's do that, and try again.

**Comment by martinpitt** [comment]
Look at that, rawhide passed! So that's already worth landing. F35 is still running, chances are that it's still the image with broken SELinux. But I'm at my wit's end how to work around it without rebooting.

**Comment by marusak** [comment]
rawhide has been passing for week now ("fixed" with [naughty](https://github.com/cockpit-project/bots/pull/2863)), see for example PR from yesterday: https://github.com/cockpit-project/cockpit-podman/pull/905
The only broken one is fedora-35

**Comment by martinpitt** [comment]
@marusak : No, look at [this log](http://artifacts.dev.testing-farm.io/d2b9b656-0d7b-487e-96d1-e59e0b81b1ad/) -- this is new from today, and this PR fixes that.

**Comment by marusak** [comment]
Interesting, because it is passing also in https://github.com/cockpit-project/cockpit-podman/pull/907 that was triggered 30 minutes ago.

**Comment by martinpitt** [comment]
Hmm, good point -- I suppose it doesn't *hurt* to upgrade conmon, as we want to test against the latest packages. But if you prefer, I can back this out again.

**Review by marusak — APPROVED** [review]
Oh right, I am not against this PR at all, I was just pointing out that I __think__ that rawhide works in general. Thanks!

**Pull request merged**
