### PR TITLE
mobile: Drop the gutter in small sizes

### PR DESCRIPTION
**Pull request by garrett**
This cuts down on the horizontal padding on small devices using Cockpit's `ct-pagesection-mobile` class for `PageSection`.

### CODE REVIEW

**Comment by marusak** [comment]
pixel tests confirmed that it worked :) Can you please update them?

**Comment by garrett** [comment]
> pixel tests confirmed that it worked :) Can you please update them?

I've tried so many times to update them, but there's no good documentation on how to do so. (There's documentation, but it glosses over that part.)

And it's different for Cockpit-Podman apparently:

```sh
~/P/c/podman images ❱ ./test/common/pixel-tests pull
fish: Unknown command: ./test/common/pixel-tests
```

**Comment by marusak** [comment]
you need to first prepare test/common => `make test/common`

**Comment by garrett** [comment]
OK, did that. It should be done (after downloading some magic URLs from @jelly, then putting them in `test/reference` and running the `./test/common/pixel-tests push` command), but I'm 75% sure that it isn't.

**Review by jelly — APPROVED** [review]

**Pull request merged**
