### PR TITLE
Makefile: Bump test/common and pkg/lib to 239

### PR DESCRIPTION
**Pull request by marusak**
Testing (and possibly fixing) fedora-34

### CODE REVIEW

**Comment by marusak** [comment]
All green at first try including rawhide :O

**Review by martinpitt — APPROVED** [review]
So it *is* possible -- things *can* work on first attempt :grinning:

**Comment by martinpitt** [comment]
Not landing yet, packit tests are still running.

**Comment by marusak** [comment]
Hmm, those urls are 404s

**Comment by martinpitt** [comment]
@TomasTomecek : Fedora 34 worked well both here and in https://github.com/cockpit-project/starter-kit/pull/432 . Sems 32/33/rawhide have been stuck for a suspicious while in both PRs. The [API request for e.g. fedora-33 here](https://api.dev.testing-farm.io/v0.1/requests/422c93cc-0988-4a42-8201-cb7ece006885) shows no progress, still pending. But that might be just stuck?

**Comment by martinpitt** [comment]
@TomasTomecek : correction -- in https://github.com/cockpit-project/starter-kit/pull/432 rawhide finished, and 32/33/34 got stuck. So it's probably just a matter of waiting a bit, the [queue](https://dashboard.packit.dev/jobs) does seem to make progress.

**Comment by TomasTomecek** [comment]
> @TomasTomecek : correction -- in [cockpit-project/starter-kit#432](https://github.com/cockpit-project/starter-kit/pull/432) rawhide finished, and 32/33/34 got stuck. So it's probably just a matter of waiting a bit, the [queue](https://dashboard.packit.dev/jobs) does seem to make progress.

Thanks for letting me know! I'm gonna add that as another requirement here: https://github.com/packit/packit-service/issues/1011 - so that you can easily tell if the job is borked or just queued.

**Pull request merged**
