### PR TITLE
Update PF to match Cockpit

### PR DESCRIPTION
**Pull request by jelly**
* [x] DownloadImage test fails
* [x] HealthCheck test fails
* [x] Fix `warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.`
* [x] Fix this [pixel test failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1361-20230725-125717-72c54fc3-fedora-38/pixeldiff.html#TestApplication-testHealthcheckSystem-healthcheck-details-mobile)

For reviewer: [pixel test changes](https://github.com/cockpit-project/pixel-test-reference/compare/2fb728a4034454eacee59c4d768a9174002965e5..56a723c6e4913ddb84dd1bd4abcdf9fdbbb52e96)

### CODE REVIEW

**Review by martinpitt — APPROVED** [review]
Yay, thanks!

**Comment by martinpitt** [comment]
Meh, [pixel diff](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1361-20230726-062504-51af508c-fedora-38-pybridge/pixeldiff.html#TestApplication-testRunImageSystem-integration) -- but that looks wrong, the temporary dir path should surely be ignored?

**Comment by jelly** [comment]
> Meh, [pixel diff](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1361-20230726-062504-51af508c-fedora-38-pybridge/pixeldiff.html#TestApplication-testRunImageSystem-integration) -- but that looks wrong, the temporary dir path should surely be ignored?

*Shakes fist* yes, the ignore rule does not match anymore ofcourse.

**Review by skobyda — APPROVED** [review]
LGTM

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
