### PR TITLE
Adjust to recent socket renaming

### PR DESCRIPTION
**Pull request by martinpitt**

### CODE REVIEW

**Comment by larskarlitski** [comment]
Is this renaming documented somewhere?

**Comment by martinpitt** [comment]
Example failure: https://fedorapeople.org/groups/cockpit/logs/pull-9849-20180817-055959-4c070f5c-cockpit-project-cockpit-podman-cockpit-fedora-28/log

**Comment by martinpitt** [comment]
@larskarlitski: They didn't mention it in the changelog, but https://src.fedoraproject.org/cgit/rpms/podman.git/commit/?id=f19a0db77f46 does the same.

**Comment by larskarlitski** [comment]
Thanks. I guess this is not *really* public API yet...

**Pull request merged**
