### PR TITLE
Replace docker.io with quay.io

### PR DESCRIPTION
**Pull request by marusak**
Docker now has strict limits for how much we can pull from it. Lets use
something different.

### CODE REVIEW

**Comment by marusak** [comment]
oh common, I though those images were just the common one, but seems neither of them exists on `registry.fedoraproject.org` nor `registry.access.redhat.com`.

**Comment by martinpitt** [comment]
Indeed registry.fedoraproject isn't very good/popular for general upstreams. How about these:

 - https://quay.io/repository/libpod/busybox?tab=info (`podman run -it --rm quay.io/libpod/busybox`)
 - https://quay.io/repository/libpod/alpine?tab=tags (`podman run -it --rm quay.io/libpod/alpine`

These seem quite reasonable to me. I didn't find registry:2 on quay, though. GitHub also has a registry now (ghcr.io), but there is no browser yet, or I didn't find it.

IMHO it would be better to pull these images during image-create, then we need to pull them less often, and at least we run into registry problems during image rebuild (where they hurt less than in project PRs).

**Comment by martinpitt** [comment]
I created a cockpit org on quay and pushed the registry:2 image [to quay.io](https://quay.io/repository/cockpit/registry?tab=info). Let's just use it from there. @marusak , if you create an account on quay.io, I'm happy to add you to the org as admin.

**Comment by martinpitt** [comment]
Lazy Saturday evening "let the bots test it for me" force-push.

**Review by martinpitt — APPROVED** [review]
That works. Formally approving, but @marusak please cross-check and land.

**Comment by marusak** [comment]
Amazing, thanks @martinpitt !

**Pull request merged**
