### PR TITLE
Makefile: Call run-tests in make check target

### PR DESCRIPTION
**Pull request by Gundersanne**
- [x] https://github.com/cockpit-project/cockpit/pull/14157

### CODE REVIEW

**Comment by martinpitt** [comment]
The cockpit PR to move run-tests landed now. This now needs to bump the test/common checkout tag, so for testing we can just check out a SHA -- and after tomorrow's release, we can use the 220 tag.

**Comment by martinpitt** [comment]
This seems to work fine locally, I pushed a temporary hack to checkout the SHA to run tests on CI.

**Comment by martinpitt** [comment]
Yay, green and proper logs! I don't see any naughties, just some retried flakes.

**Comment by martinpitt** [comment]
Adding "blocked" again, let's finish/land this after cockpit 220 release tomorrow?

**Comment by marusak** [comment]
:heart: thanks!
Lets indeed wait until 220 is tagged (later today) and do this properly.

**Pull request merged**
