### PR TITLE
tasks: Drop issue-scan

### PR DESCRIPTION
**Pull request by martinpitt**
This is now done by webhooks and AMQP.

### CODE REVIEW

**Comment by Gundersanne** [comment]
Shouldn't we enable an issues webhook for this repo then?

**Comment by martinpitt** [comment]
@Gundersanne: I added "Issues" events to the webhooks of cockpit-{podman,starter-kit,composer}. Does that need any other changes? Not sure what you mean by the "--repo" thing?

**Comment by martinpitt** [comment]
Setting to blocked, this first needs some adjustments to tests-scan to take the repo from issue_data.

**Comment by martinpitt** [comment]
I re-dropped the issues webhook from all projects, as this wreaks havoc: https://github.com/cockpit-project/cockpit/pull/724

**Comment by Gundersanne** [comment]
and a successful run here #187

**Pull request merged**
