### PR TITLE
Packit fixes

### PR DESCRIPTION
**Pull request by marusak**
I just want to run `fedora-33/rawhide` but though why not fixing this? :)

### CODE REVIEW

**Review by martinpitt — DISMISSED** [review]
Thanks!

**Comment by marusak** [comment]
Ok, two failed tests. I'll debug them locally and push fix here.

**Comment by marusak** [comment]
There is some weird issue, that the first test always fails. Second test or retry works just fine. I saw it in CI as well. I am playing with it, it seems like race but I am having no luck solving it yet. Pushing to get one more run.

**Comment by marusak** [comment]
Ok, so the very first test fails as expected and also testDownload is failing. It fails the same way, not sure though why. Looking.

**Review by martinpitt — APPROVED** [review]
Thanks!

**Comment by martinpitt** [comment]
[testDownloadImage](https://logs.cockpit-project.org/logs/pull-648-20210108-142833-d09bd223-rhel-8-4/log.html#5-2) failed on rhel-8-4, retrying once to compare.

**Comment by martinpitt** [comment]
FTR: the packit fixes don't seem to work, but I'm happy to address that in #649.

**Comment by marusak** [comment]
F33 rawhide is green! I feel like there is going to be some flakiness to it, but it is not required context, so let's go with this.
Also I'll open issue about that first failing test.

**Pull request merged**
