### PR TITLE
Is sassc installed?

### PR DESCRIPTION
**Pull request by marusak**
I've tried the new container and it worked, lets see if it is deployed

### CODE REVIEW

**Comment by marusak** [comment]
:man_shrugging: locally it works, in sandbox it works, here it does not work

**Comment by martinpitt** [comment]
I'm also trying this in PR #649. I am not sure whether we need a separate rule to output the name after all, as the error message says "the single line of the output". So in #649 I split it again.

**Comment by marusak** [comment]
> I am not sure whether we need a separate rule to output the name after all, as the error message says "the single line of the output". So in #649 I split it again.

Ah right, you are trying it out as well. It it fine when it is at the of the log, does not need to be separate command (from my local tests). I am trying it now with separate command in packit.yaml with `find` as 1. If it fails to be created, this command should not find it 2. Maybe since not all logs are parsed from `make dist-gzip` it might not see it.

**Comment by marusak** [comment]
Ok, `find` did not find it, that means `make dist-gzip` still fails.

**Comment by TomasTomecek** [comment]
playing with this a little bit more and finally getting to something:
```
ERROR in ./src/Containers.scss                                                                                                                                                                
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):                                                                                                             
ModuleBuildError: Module build failed (from ./lib/sassc-loader.js):                                                                                                                           
Error: EACCES: permission denied, mkdtemp 'sassc-loader.XXXXXX'                                                                                                                               
    at Object.mkdtempSync (fs.js:1847:3)                                                                                                                                                      
    at Object.module.exports (/src/lib/sassc-loader.js:9:24)                                                                                                                                  
    at /src/node_modules/webpack/lib/NormalModule.js:316:20                                                                                                                                   
    at /src/node_modules/loader-runner/lib/LoaderRunner.js:367:11                                                                                                                             
    at /src/node_modules/loader-runner/lib/LoaderRunner.js:233:18                                                                                                                             
    at runSyncOrAsync (/src/node_modules/loader-runner/lib/LoaderRunner.js:143:3)                                                                                                             
    at iterateNormalLoaders (/src/node_modules/loader-runner/lib/LoaderRunner.js:232:2)                                                                                                       
    at Array.<anonymous> (/src/node_modules/loader-runner/lib/LoaderRunner.js:205:4)                                                                                                          
    at Storage.finished (/src/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)                                                                                               
    at /src/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9                                                                                                                   
    at /src/node_modules/graceful-fs/graceful-fs.js:123:16                                                                                                                                    
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)  
```
this looks like a problem with openshift's anyuid + the truncated output seems indeed to be caused by npm's black sorcery

**Comment by martinpitt** [comment]
@TomasTomecek : OOh! So `mktemp` is broken in the container?

**Comment by TomasTomecek** [comment]
> @TomasTomecek : OOh! So `mktemp` is broken in the container?

I thought that we are hitting openshift's anyuid but it wasn't the case - I tried to mimic how openshift runs containers on my own but failed, hence the error above, sorry for the noise.

The actual problem is, that node segfualts on being out of memory: https://github.com/packit/packit-service/issues/917#issuecomment-760948922

**Comment by martinpitt** [comment]
I sent #656 to do some fixes which have proven to work on packit staging. I think we can close this now?

**Pull request closed without merging**
