### PR TITLE
Replace docker.io with quay.io

### PR DESCRIPTION
**Pull request by mvollmer**
Docker now has strict limits for how much we can pull from it. Lets use
quay.io instead.

### CODE REVIEW

**Comment by martinpitt** [comment]
That's a backport of commit 152cdacef68e08afe27d54c3cfd3ed1743053cad

**Comment by marusak** [comment]
It might need a few more backports

**Comment by mvollmer** [comment]
> It might need a few more backports

Yeah, I have done this very sloppily, and just ignored all parts that have merge conflicts...

**Comment by mvollmer** [comment]
Green, but let's run the tests again, just to be certain.

**Review by marusak — APPROVED** [review]
Thanks!

**Pull request merged**
