### PR TITLE
test: Drop obsolete HACK

### PR DESCRIPTION
**Pull request by marusak**
Checking if it is still happening as asked in https://github.com/containers/podman/issues/8762#issuecomment-762304421
Also checking if packit is now working.

### CODE REVIEW

**Comment by marusak** [comment]
The hack is still needed.
Packit went further, not green yet though. We can keep this opened and retry packit if the fix is coming soon.

**Comment by martinpitt** [comment]
/packit build

packit has been sitting at "submitting the tests" for two days now. @TomasTomecek says this is due to some issues with the testing farm. Trying again.

**Comment by martinpitt** [comment]
Hmm, the [job queue](https://dashboard.packit.dev/jobs) doesn't look good -- seems they haven't been actually served for a long time already.

**Pull request closed without merging**
