### PR TITLE
Check for NPM dependency updates

### PR DESCRIPTION
**Pull request by cockpituous**
Check for any outstanding update of point version of any outstanding NPM package dependency
 * [x] npm-update

### CODE REVIEW

**Comment by cockpituous** [comment]
npm-update react-dom done: https://github.com/cockpituous/cockpit-podman/commits/npm-update-react-dom-20190809-033838

**Comment by cockpituous** [comment]
Error accessing /repos/cockpit-project/cockpit-podman/pulls
  Status: 422
  Reason: Unprocessable Entity
  Response: {"message":"The specified issue is already attached to a pull request.","errors":[{"value"None,"resource":"PullRequest","field":"issue","code":"invalid"}],"documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}: https://209.132.184.41:8493/logs/npm-update-175-20190809-033737/

**Comment by cockpituous** [comment]
npm-update in progress on 4-ci-srv-01.
Log: https://209.132.184.41:8493/logs/npm-update-175-20190809-033838/

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```
.babelrc:                "@babel/preset-react"]
.eslintrc.json:    "extends": ["eslint:recommended", "standard", "standard-react"],
.eslintrc.json:    "plugins": ["flowtype", "react"],
.eslintrc.json:        "react/jsx-indent": ["error", 4],
.eslintrc.json:        "react/jsx-curly-spacing": "off",
.eslintrc.json:        "react/jsx-indent-props": "off",
.eslintrc.json:        "react/prop-types": "off",
.eslintrc.json:        "react/jsx-no-bind": "off"
lib/cockpit-components-file-autocomplete.jsx:import React from "react";
lib/cockpit-components-listing.jsx:import React from 'react';
lib/cockpit-components-listing.jsx: *     columns to show, can be a string, react component or object with { name: 'name', 'header': false }
lib/cockpit-components-listing.jsx: *     - name tab name (has to be unique in the entry, used as react key)
lib/cockpit-components-listing.jsx: *     - renderer react component
lib/cockpit-components-select.jsx:import React from 'react';
lib/cockpit-components-select.jsx: * Dynamic lists should make sure to also provide 'key' props for react to use
package.json:    "@babel/preset-react": "^7.0.0",
package.json:    "eslint-config-standard-react": "^7.0.2",
package.json:    "eslint-plugin-react": "^7.12.4",
package.json:    "patternfly-react": "1.19.1",
package.json:    "react": "16.9.0",
package.json:    "react-addons-css-transition-group": "15.6.2",
package.json:    "react-addons-transition-group": "15.6.2",
package.json:    "react-dom": "16.8.6",
src/ContainerCommitModal.jsx:import React from 'react';
src/ContainerCommitModal.jsx:import { Modal, Button, FormGroup, FormControl } from 'patternfly-react';
src/ContainerDeleteModal.jsx:import React from 'react';
src/ContainerDeleteModal.jsx:import { Button, Modal } from 'patternfly-react';
src/ContainerDetails.jsx:import React from 'react';
src/ContainerHeader.jsx:import React from 'react';
src/ContainerRemoveErrorModal.jsx:import React from 'react';
src/ContainerRemoveErrorModal.jsx:import { Button, Modal } from 'patternfly-react';
src/ContainerTerminal.jsx:import React from 'react';
src/Containers.jsx:import React from 'react';
src/Containers.jsx:import ReactDOM from "react-dom";
src/Containers.jsx:import { Alert } from 'patternfly-react';
src/Dropdown.jsx:import React from 'react';
src/Dropdown.jsx:import { DropdownButton, MenuItem } from 'patternfly-react';
src/ImageDeleteModal.jsx:import React from 'react';
src/ImageDeleteModal.jsx:import { Button, Modal } from 'patternfly-react';
src/ImageDetails.jsx:import React from 'react';
src/ImageRemoveErrorModal.jsx:import React from 'react';
src/ImageRemoveErrorModal.jsx:import { Button, Modal } from 'patternfly-react';
src/ImageRunModal.jsx:import React from 'react';
src/ImageRunModal.jsx:import { Button, Modal } from 'patternfly-react';
src/ImageSearchModal.jsx:import React from 'react';
src/ImageSearchModal.jsx:import { Button, ListGroup, ListGroupItem, Modal } from 'patternfly-react';
src/ImageSecurity.jsx:import React from 'react';
src/Images.jsx:import React from 'react';
src/Images.jsx:import { Button } from 'patternfly-react';
src/Notification.jsx:import React from 'react';
src/Notification.jsx:import { Alert } from 'patternfly-react';
src/app.jsx:import React from 'react';
src/app.jsx:import { ToastNotificationList, ToastNotification } from 'patternfly-react';
src/index.es6:import React from 'react';
src/index.es6:import ReactDOM from 'react-dom';
```

**Comment by cockpituous** [comment]
npm-update react done: https://github.com/cockpituous/cockpit-podman/commits/npm-update-react-20190809-033939

**Comment by cockpituous** [comment]
Error accessing /repos/cockpit-project/cockpit-podman/pulls
  Status: 422
  Reason: Unprocessable Entity
  Response: {"message":"The specified issue is already attached to a pull request.","errors":[{"value"None,"resource":"PullRequest","field":"issue","code":"invalid"}],"documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}: https://209.132.184.41:8493/logs/npm-update-175-20190809-033838/

**Comment by marusak** [comment]
The same thing already landed. Weirdly enough github does not say it has conflict.

**Pull request closed without merging**
