### PR TITLE
Implement text filter in ContainerHeader

### PR DESCRIPTION
**Pull request by QiWang19**

### CODE REVIEW

**Comment by QiWang19** [comment]
@martinpitt  PTAL

**Comment by QiWang19** [comment]
```
        # test filter
        b.wait_present(".content-filter div input")
        b.set_val(".content-filter div input", "swamp")
        b.wait_present("#containers-containers")
        b.wait_not_in_text("#containers-containers", "alpine:latest")
```
Is this the right method to test the filter, I got the screenshot because test failed, but cannot replicate the this problem in `http://127.0.0.2:9091`
testapplication-testbasic-fedora-28-127 0 0 2-2201-fail

screenshot from 2018-10-02 20-31-15

**Comment by martinpitt** [comment]
Use `.set_input_text` instead of `.set_val()`. The latter doesn't work with React, as it circumvents the key event handlers.

**Comment by QiWang19** [comment]
I also failed to show the containers come back after set input value to ""  
```
b.set_input_text(".content-filter div input", "")
b.wait_in_text("#containers-containers", "alpine:latest")
```
testapplication-testbasic-fedora-28-127 0 0 2-2201-fail

**Pull request closed without merging**
