### PR TITLE
warning dialogs: remove "Please"

### PR DESCRIPTION
**Pull request by jelly**
image

### CODE REVIEW

**Review by marusak — DISMISSED** [review]
Looks good to me, thanks!
I did `git grep -i please pkg` in cockpit and there is bunch of such messages. Do we want to adjust these as well?

**Comment by jelly** [comment]
> Looks good to me, thanks! I did `git grep -i please pkg` in cockpit and there is bunch of such messages. Do we want to adjust these as well?

Fixed.

**Comment by garrett** [comment]
Changed the title to reflect what this PR is about. (We should try to not have generic headings; it makes it harder to understand what the changes are supposed to be, and it makes it even more difficult to come back to PRs that are open for a while, which this one isn't... as I'll approve it too. :wink:)

**Review by garrett — APPROVED** [review]
_Please_ accept my +1 :+1: :wink:

**Pull request merged**
