### PR TITLE
package.json: Update patternfly package dependency

### PR DESCRIPTION
**Pull request by cockpituous**
Check for any outstanding update of point version of any outstanding NPM package dependency
 * [x] npm-update

### CODE REVIEW

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```
lib/cockpit-components-file-autocomplete.jsx:import { FormGroup, HelpBlock, TypeAheadSelect } from "patternfly-react";
lib/cockpit-components-listing.jsx: * https://www.patternfly.org/v3/pattern-library/content-views/list-view/index.html
lib/page.css:@import "../node_modules/@patternfly/patternfly/patternfly-variables.css";
lib/page.css:/* HACK: Workaround for https://github.com/patternfly/patternfly/issues/174*/
lib/page.css:/* HACK: https://github.com/patternfly/patternfly/issues/255 */
lib/page.css:/* See: https://github.com/patternfly/patternfly-next/issues/2325 */
lib/variables.less:@import (less) "../node_modules/patternfly/dist/less/variables.less";
package.json:    "@patternfly/patternfly": "^2.71.5",
package.json:    "@patternfly/react-core": "^3.153.3",
package.json:    "patternfly": "3.59.5",
package.json:    "patternfly-react": "2.39.15",
src/ContainerCommitModal.jsx:import { Modal, FormGroup, FormControl } from 'patternfly-react';
src/ContainerCommitModal.jsx:import { Button } from '@patternfly/react-core';
src/ContainerDeleteModal.jsx:import { Modal } from 'patternfly-react';
src/ContainerDeleteModal.jsx:import { Button } from '@patternfly/react-core';
src/ContainerRemoveErrorModal.jsx:import { Modal } from 'patternfly-react';
src/ContainerRemoveErrorModal.jsx:import { Button } from '@patternfly/react-core';
src/Containers.jsx:import { Button } from '@patternfly/react-core';
src/Dropdown.jsx:} from '@patternfly/react-core';
src/ImageDeleteModal.jsx:import { Modal } from 'patternfly-react';
src/ImageDeleteModal.jsx:import { Button } from '@patternfly/react-core';
src/ImageRemoveErrorModal.jsx:import { Modal } from 'patternfly-react';
src/ImageRemoveErrorModal.jsx:import { Button } from '@patternfly/react-core';
src/ImageRunModal.jsx:import { Modal } from 'patternfly-react';
src/ImageRunModal.jsx:import { Button } from '@patternfly/react-core';
src/ImageSearchModal.jsx:import { ListGroup, ListGroupItem, Modal } from 'patternfly-react';
src/ImageSearchModal.jsx:import { Button } from '@patternfly/react-core';
src/Images.jsx:import { Button } from '@patternfly/react-core';
src/Notification.jsx:import { Alert, AlertActionCloseButton } from '@patternfly/react-core';
src/app.jsx:import { ToastNotificationList } from 'patternfly-react';
src/app.jsx:} from '@patternfly/react-core';
src/app.jsx:import { ExclamationCircleIcon } from '@patternfly/react-icons';
src/index.html:    <link rel="stylesheet" href="../base1/patternfly.css">
src/podman.scss:/* workaround: make text red for select if contained in has-error, not in patternfly */
```

**Comment by marusak** [comment]
meh:
```
Process 25936 (exe) of user 1000 dumped core.
Stack trace of thread 25942:
#0  0x000055fb2cb20251 runtime.raise (podman)
#1  0x000055fb2cb061fd runtime.sigfwdgo (podman)
#2  0x000055fb2cb05340 runtime.sigtrampgo (podman)
#3  0x000055fb2cb20543 runtime.sigtramp (podman)
#4  0x00007f4072c0fb20 __restore_rt (libpthread.so.0)
#5  0x000055fb2cb20251 runtime.raise (podman)
#6  0x000055fb2cb05e0a runtime.crash (podman)
#7  0x000055fb2caf0496 runtime.fatalpanic (podman)
#8  0x000055fb2caefe56 runtime.gopanic (podman)
#9  0x000055fb2cac6741 runtime.chansend (podman)
#10 0x000055fb2cac6145 runtime.chansend1 (podman)
#11 0x000055fb2da883af github.com/containers/libpod/pkg/rootlessport.parent.func1 (podman)
#12 0x000055fb2da878b8 github.com/containers/libpod/pkg/rootlessport.parent (podman)
#13 0x000055fb2da88228 github.com/containers/libpod/pkg/rootlessport.init.0.func1 (podman)
#14 0x000055fb2dddaacb main.main (podman)
#15 0x000055fb2caf1bc6 runtime.main (podman)
#16 0x000000c00008e000 n/a (n/a)
#17 0x0000000000000000 n/a (n/a)
Wrote JS log to TestApplication-testRunImageUser-fedora-31-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestApplication-testRunImageUser-fedora-31-127.0.0.2-2201-FAIL.log.gz
Core dumps downloaded to /build/cockpit-project/bots/make-checkout-workdir/TestApplication-testRunImageUser-fedora-31-127.0.0.2-2201-FAIL.core
> warning: transport closed: disconnected
Warning: Stopping cockpit.service, but it can still be activated by:
  cockpit.socket
Traceback (most recent call last):
  File "test/common/testlib.py", line 878, in tearDown
    self.check_journal_messages()
  File "test/common/testlib.py", line 1072, in check_journal_messages
    raise Error("FAIL: Test completed, but found unexpected journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
Process 25936 (exe) of user 1000 dumped core.
```

**Comment by marusak** [comment]
argh, it is reported, but of course I again put there parentheses...
https://github.com/cockpit-project/bots/commit/8cd27abbd407ea27d64ccfdbe58332559694dd00

**Comment by marusak** [comment]
oh wait what? It cannot be it, we have a lot of patterns like `Traceback (most recent call last):`...

**Comment by martinpitt** [comment]
@marusak: Naughty patterns are not regexps, more like globs. We only support `*` in there.

**Pull request closed without merging**
