### PR TITLE
test: reduce line length in tests

### PR DESCRIPTION
**Pull request by jelly**
To have a successful ruff run, we will need to reduce the line length to 118 characters. This PR fixes 49 violations, a follow up will be required to complete it but as tests are flaky and we will have many retries let's do it in parts.

### CODE REVIEW

**Review by martinpitt — APPROVED** [review]
Thanks! Looks nice. I did the first round of retries, but there's some green already.

**Comment by jelly** [comment]
> Thanks! Looks nice. I did the first round of retries, but there's some green already.

Yeah, should hit green. I'll finish up the rest today

**Review by martinpitt — APPROVED** [review]
A bit strange to squash the pixel updates into a "reduce line lenght" commit, but I'll take it :grin:  thanks!

**Comment by jelly** [comment]
Ugh, yeah should have been a separate commit..

**Comment by martinpitt** [comment]
[rhel4edge](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1311-20230622-103141-f5caf688-rhel4edge/log.html) finished, but github missed the status update.

**Pull request merged**
